[package]
authors.workspace = true
description = "Fork of sp-runtime's Header type with a custom hash function that's felt aligned for our wormhole circuits"
edition.workspace = true
homepage.workspace = true
license = "Apache-2.0"
name = "qp-header"
publish = false
repository.workspace = true
version = "0.1.0"

[dependencies]
codec = { features = ["derive"], workspace = true }
log.workspace = true
p3-field = { workspace = true }
p3-goldilocks = { workspace = true }
qp-poseidon = { workspace = true, features = ["serde"] }
qp-poseidon-core = { workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
sp-core = { features = ["serde"], workspace = true }
sp-runtime = { features = ["serde"], workspace = true }

[dev-dependencies]
hex = { workspace = true }
serde_json = { workspace = true, default-features = false, features = [
	"alloc",
	"std",
] }


[features]
default = ["serde", "std"]
std = [
	"codec/std",
	"qp-poseidon/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std"
]
